IDENTIFICATION DIVISION.
PROGRAM-ID. IncrementProgram.

DATA DIVISION.
WORKING-STORAGE SECTION.
01 i PIC 9(10) VALUE 0.
01 target PIC 9(10).
01 quotient PIC 9(10).
01 rem PIC 9(10).

PROCEDURE DIVISION.
ACCEPT target FROM COMMAND-LINE
PERFORM UNTIL i = target
    ADD 1 TO i
    ADD 1 TO i *> should be bitwise or 1 but no bit-or in cobol :/
END-PERFORM.
DISPLAY i
STOP RUN.
