name: Do the thing in CI

on:
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull "ghcr.io/${{ github.actor }}/count-base:latest" || true
      - uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: "ghcr.io/${{ github.actor }}/count-base:latest"

  run:
    needs: ['build-base-image']
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/${{ github.actor }}/count-base:latest"
    strategy:
      fail-fast: false
      matrix:
        build:
          - assembly
          - bun
          - clang
          - cobol
          - coffeescript
          - crystal
          - deno
          - erlang
          - fortran
          - gcc
          - go
          - haskell
          - java
          - julia
          - kotlin
          - nim
          - node
          - perl
          - php
          - prolog
          - python3
          - ruby
          - rust
          - scala
          - smalltalk
          # - tcl
          - zig
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # install dependencies
      - uses: extractions/setup-just@v1
      - uses: oven-sh/setup-bun@v1
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "~1"
      # do the thing
      - run: just measure ${{ matrix.build }}
      # report
      - uses: actions/upload-artifact@v3
        with:
          path: "${{ matrix.build }}.json"

  report:
    needs: ["run"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Results
        uses: actions/download-artifact@v3
        with:
          path: .
      - run: sudo apt-get install nodejs
      - name: Generate Summary
        run: |
          cd scripts
          npm install
          node ./summary.js --results ../artifact > summary.txt
          cat summary.txt
      - uses: actions/upload-artifact@v3
        with:
          path: scripts/summary.txt
