name: Do the thing in CI

on:
  push:
    branches: ["master", "docker"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: acheronfail/count
      volumes:
        /var/count:/data
    strategy:
      fail-fast: false
      matrix:
        build:
          - assembly
          # - bun
          # - c-gcc
          # - c-clang
          # - cpp-gcc
          # - cpp-clang
          # - cobol
          # - coffeescript
          # - crystal
          # - csharp
          # - deno
          # - erlang
          # - forth
          # - fortran
          # - go
          # - haskell
          # - java
          # - julia
          # - kotlin
          # - lua
          # - nim
          # - node
          # - pascal
          # - perl
          # - php
          # - prolog
          # - python3
          # - ruby
          # - rust
          # - scala
          # - smalltalk
          # - tcl
          # - zig
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: pwd
      # do the thing
      # - run: just test    ${{ matrix.build }}
      # - run: just measure ${{ matrix.build }}
      # # report
      # - uses: actions/upload-artifact@v3
      #   with:
      #     path: "${{ matrix.build }}.json"

  report:
    needs: ["run"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Results
        uses: actions/download-artifact@v3
        with:
          path: .
      - run: sudo apt-get update && sudo apt-get install -y nodejs
      - name: Generate Summary
        run: |
          cd scripts
          npm install
          node ./summary.js --results ../artifact > summary.txt
          cat summary.txt
      - uses: actions/upload-artifact@v3
        with:
          path: scripts/summary.txt
