name: Do the thing in CI

on:
  push:
    branches: ['master']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        # do the slow ones first, to make the overall build quicker
        build:
          # - tcl
          - prolog
          - smalltalk
          - python3
          - julia
          - perl
          - swift
          - cobol
          - ruby
          - haskell
          - forth
          - lua
          - ocaml
          - php
          - erlang
          - crystal
          - scala
          - csharp
          - coffeescript
          - kotlin
          - java
          - deno
          - node
          - go
          - bun
          - pony
          - fortran
          - rust
          - swiftc
          - vala
          - cpp-clang
          - cpp-gcc
          - c-clang
          - c-gcc
          - nim
          - pascal
          - zig
          - assembly
    runs-on: ubuntu-latest
    container:
      image: acheronfail/count
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # really github? why do you override $HOME?
      # https://github.com/actions/runner/issues/863
      - name: Setup environment
        run: |
          echo HOME=/root >> $GITHUB_ENV
          WHAT=${{ matrix.build }}
          echo WHAT=${WHAT##*_} >> $GITHUB_ENV
      # do the thing
      - run: just test    ${{ env.WHAT }}
      - run: just measure ${{ env.WHAT }}
      # report
      - uses: actions/upload-artifact@v3
        with:
          path: 'results/${{ env.WHAT }}.json'

  report:
    needs: ['run']
    runs-on: ubuntu-latest
    permissions:
      # needed for creating the github release
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Results
        uses: actions/download-artifact@v3
        with:
          path: .
      - run: sudo apt-get update && sudo apt-get install -y nodejs
      - name: Generate Summary
        run: |
          cd scripts
          npm start -- --results ../artifact
          cat summary.md
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.run_number }}
          body_path: scripts/summary.md
          files: artifact/*.json
          draft: ${{ github.ref_name != 'master' }}
          prerelease: ${{ github.ref_name != 'master' }}
